// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPI_Programación3.DBContext;

#nullable disable

namespace TPI_Programación3.Migrations
{
    [DbContext(typeof(TridentExchangeDBContext))]
    [Migration("20221103222926_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("TPI_Programación3.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electrodomésticos",
                            OfferQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vehiculo",
                            OfferQuantity = 5
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inmueble",
                            OfferQuantity = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mundial",
                            OfferQuantity = 20
                        });
                });

            modelBuilder.Entity("TPI_Programación3.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferedItem")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electrodoméstico",
                            CreatorEmail = "alejo@gmail.com",
                            Description = "Es literalmente una licuadora",
                            ImgLink = "https://url24.top/vJGZp",
                            Name = "Licuadora",
                            PreferedItem = "Batidora"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electrodoméstico",
                            CreatorEmail = "gaston_elcapo@gmail.com",
                            Description = "Sirve para tostar pan",
                            ImgLink = "https://url24.top/AvyPV",
                            Name = "Tostadora",
                            PreferedItem = "Tostadora"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Vehiculo",
                            CreatorEmail = "elmassi@gmail.com",
                            Description = "Corsita 2009",
                            ImgLink = "https://url24.top/hqPKD",
                            Name = "Auto",
                            PreferedItem = "Auto"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Inmueble",
                            CreatorEmail = "milton_tucson_tuki@gmail.com",
                            Description = "Casa dos pisos",
                            ImgLink = "https://url24.top/lPhra",
                            Name = "Casa",
                            PreferedItem = "Vivienda"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mundial",
                            CreatorEmail = "pedrito@gmail.com",
                            Description = "La figurita de Messi",
                            ImgLink = "https://url24.top/TvJrw",
                            Name = "Figurita",
                            PreferedItem = "Mundial"
                        });
                });

            modelBuilder.Entity("TPI_Programación3.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alejo@gmail.com",
                            FullName = "Alejo",
                            Password = "3c9909afec25354d551dae21590bb26e38d53f2173b8d3dc3eee4c047e7ab1c1eb8b85103e3be7ba613b31bb5c9c36214dc9f14a42fd7a2fdb84856bca5c44c2",
                            Role = "Common"
                        },
                        new
                        {
                            Id = 2,
                            Email = "gaston_elcapo@gmail.com",
                            FullName = "Gaston",
                            Password = "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f",
                            Role = "Common"
                        },
                        new
                        {
                            Id = 3,
                            Email = "elmassi@gmail.com",
                            FullName = "Maxi",
                            Password = "ca9879bd727ba3bd815f05fe6b9e4640c774b61cc8f141295542cefc1b7b8fc6e3daf3f656555cdec355894e7af48964e88994d960f41ba8f61f7a05d5ddbd07",
                            Role = "Common"
                        },
                        new
                        {
                            Id = 4,
                            Email = "milton_tucson_tuki@gmail.com",
                            FullName = "Milton",
                            Password = "b5ba77af1f7bda735894e746a199acb1d2c836424da2fc46bebb55423dccbff871877a30fab77a31e47b0a29ea0154882e532e9a29b220a8f2958773313bbb2a",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = 5,
                            Email = "pedrito@gmail.com",
                            FullName = "Pedro",
                            Password = "d67e72421ee3e9e68ca4b6e8da288f406ad976f5371945790d95861398d39064a4fe66f021ce87b63417150545df9a98a76da5cf012f7c908851647bcc2fa4fd",
                            Role = "Administrator"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
